use std::f64;

use serde::{Deserialize, Serialize};
use crate::weapon_params::GuardPlateShape;

#[derive(Clone, Copy, Deserialize, Serialize, PartialEq)]
pub struct ModelParams {
    pub v_mirrored: bool,

    pub pommel_extension: f64,
    pub pommel_radius: f64,

    pub handle_bottom_limit: f64,
    pub handle_radius: f64,
    pub handle_grip_offset: f64,
    pub handle_grip_y_scale: f64,

    pub guard_bottom: f64,
    pub guard_front_stop: f64,
    pub guard_back_stop: f64,
    pub guard_left_stop: f64,
    pub guard_right_stop: f64,
    pub guard_effect_radius: f64,
    pub guard_x_offset: f64,
    pub guard_x_scale: f64,
    pub guard_z_offset: f64,
    pub guard_z_scale: f64,
    pub has_guard: bool,
    pub has_guard_bar: bool,
    pub guard_bar_front_offset: f64,
    pub guard_bar_back_offset: f64,
    pub guard_bar_left_offset: f64,
    pub guard_bar_right_offset: f64,
    pub guard_bar_radius: f64,
    pub guard_bar_x_scale: f64,
    pub guard_bar_z_scale: f64,
    pub guard_bar_y_scale: f64,
    pub guard_bar_thickness: f64,
    pub guard_bar_height: f64,
    pub guard_bar_curves_back: bool,
    pub guard_bar_bottom_offset: f64,
    pub guard_plate_shape: GuardPlateShape,
    pub guard_plate_curvature: f64,

    pub blade_bottom: f64,
    pub blade_radius: f64,
    pub blade_front_width: f64,
    pub blade_back_width: f64,
    pub blade_left_top_slope: f64,
    pub blade_right_top_slope: f64,
    pub blade_scale_front_left_decrement: f64,
    pub blade_scale_front_right_decrement: f64,
    pub blade_scale_back_left_decrement: f64,
    pub blade_scale_back_right_decrement: f64,
    pub blade_height: f64,
    pub blade_curvature: f64,
    pub blade_lean: f64,

    pub blade_serated_left: bool,
    pub blade_serated_left_size: f64,
    pub blade_serated_left_count: f64,
    pub blade_serated_right: bool,
    pub blade_serated_right_size: f64,
    pub blade_serated_right_count: f64,
    pub blade_spiked_left: bool,
    pub blade_spiked_left_size: f64,
    pub blade_spiked_left_count: f64,
    pub blade_spiked_right: bool,
    pub blade_spiked_right_size: f64,
    pub blade_spiked_right_count: f64,
}

impl Default for ModelParams {
    fn default() -> Self {
        ModelParams {
            v_mirrored: false,
            pommel_extension: 2.0,
            pommel_radius: 2.5,
            handle_bottom_limit: 5.5,
            handle_radius: 0.5,
            handle_grip_offset: 0.2,
            handle_grip_y_scale: 2.0,
            guard_bottom: 4.0,
            guard_front_stop: 2.0,
            guard_back_stop: 2.0,
            guard_left_stop: 5.0,
            guard_right_stop: 5.0,
            guard_effect_radius: 2.0,
            guard_x_offset: 2.0,
            guard_x_scale: 1.0,
            guard_z_offset: 2.0,
            guard_z_scale: 3.0,
            guard_bar_back_offset: 0.0,
            guard_bar_front_offset: 0.0,
            guard_bar_left_offset: 2.0,
            guard_bar_right_offset: 0.0,
            guard_bar_radius: 0.5,
            guard_bar_y_scale: 0.8,
            guard_bar_thickness: 0.3,
            guard_bar_height: 3.0,
            guard_bar_curves_back: true,
            guard_plate_shape: GuardPlateShape::Flat,
            guard_plate_curvature: 1.0,
            blade_bottom: 15.0,
            blade_radius: 5.0,
            blade_front_width: 0.5,
            blade_back_width: 0.5,
            blade_left_top_slope: 2.0,
            blade_right_top_slope: 2.0,
            blade_scale_front_left_decrement: 2.0,
            blade_scale_front_right_decrement: 2.0,
            blade_scale_back_left_decrement: 2.0,
            blade_scale_back_right_decrement: 2.0,
            blade_height: 25.0,
            blade_curvature: -20.0,
            blade_lean: 0.0,
            guard_bar_bottom_offset: 1.0,
            guard_bar_x_scale: 1.0,
            guard_bar_z_scale: 0.1,
            has_guard: true,
            has_guard_bar: true,
            blade_serated_left: false,
            blade_serated_left_count: 1.0,
            blade_serated_left_size: 2.0,
            blade_serated_right: false,
            blade_serated_right_count: 1.0,
            blade_serated_right_size: 2.0,
            blade_spiked_left: false,
            blade_spiked_left_count: 1.0,
            blade_spiked_left_size: 1.0,
            blade_spiked_right: false,
            blade_spiked_right_count: 1.0,
            blade_spiked_right_size: 2.0,
        }
    }
}
